// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package user

import (
	"hiveify-core/api/user"
)

// ControllerV1 用户controller
type ControllerV1 struct{}

// NewV1 创建用户controller
func NewV1() user.IUserV1 {
	return &ControllerV1{}
}
