// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hiveify-core/internal/dao/internal"
)

// internalUserNodeDao is internal type for wrapping internal DAO implements.
type internalUserNodeDao = *internal.UserNodeDao

// userNodeDao is the data access object for table t_user_node.
// You can define custom methods on it to extend its functionality as you wish.
type userNodeDao struct {
	internalUserNodeDao
}

var (
	// UserNode is globally public accessible object for table t_user_node operations.
	UserNode = userNodeDao{
		internal.NewUserNodeDao(),
	}
)

// Fill with you ideas below.
